services:
  app:
    build: .
    container_name: product-service-app
    volumes:
      - .:/var/www
    networks:
      - laravel-net
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:stable-alpine
    container_name: product-service-nginx
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: product-service-db
    environment:
      MYSQL_DATABASE: product_service
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - product_db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  laravel-net:
    external: true

volumes:
  product_db_data:
