services:
  order_app:
    build: .
    container_name: order-service-app
    volumes:
      - .:/var/www
    networks:
      - laravel-net
    depends_on:
      - order_db

  order_web:
    image: nginx:stable-alpine
    container_name: order-service-nginx
    ports:
      - "8002:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net
    depends_on:
      - order_app

  order_db:
    image: mysql:8
    container_name: order-service-db
    environment:
      MYSQL_DATABASE: order_service
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - laravel-net

networks:
  laravel-net:
    external: true

volumes:
  db_data:
