services:
  app:
    build: .
    container_name: user-service-app
    volumes:
      - .:/var/www
    networks:
      - laravel-net
    depends_on:
      - db

  web:
    image: nginx:stable-alpine
    container_name: user-service-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: user-service-db
    environment:
      MYSQL_DATABASE: user_service
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-net

networks:
  laravel-net:
    external: true

volumes:
  db_data:
